let questions = [
  {
    numb: 1,
    question: "Hva heter den første vinen gutta lagde?",
    img: "1.png",
    answer: "D. Guttas Drue",
    options: [
      "A. Guttas Berry",
      "B. Guttas Rose",
      "C. Guttas Rouge",
      "D. Guttas Drue",
    ],
  },
  {
    numb: 2,
    question: "Hvilken vin har vi ikke laget?",
    img: "2.JPG",
    answer: "D. Guttas Chardonnay",
    options: [
      "A. Guttas Hvite",
      "B. Guttas Rose",
      "C. Guttas Riesling",
      "D. Guttas Chardonnay",
      "E. Guttas Rouge",
      "F. Guttas Piesporter",
    ],
  },
  {
    numb: 3,
    question: "Hvem er økonomiansvarlig i Druekompaniet?",
    img: "3.JPG",
    answer: "B. Mario El Boss",
    options: [
      "A. Gjerry Mc.Nugget",
      "B. Mario El Boss",
      "C. Ola Fire",
      "D. Herry Fjeld",
    ],
  },
  {
    numb: 4,
    question: "Hvilken av de nedenfor har hatt høyest % by vol ?",
    img: "4.JPG",
    answer: "C. Guttas Hvite",
    options: [
      "A. Guttas Berry",
      "B. Guttas Piesporter",
      "C. Guttas Hvite",
      "D. Guttas Riesling",
    ],
  },
  {
    numb: 5,
    question: "Hvor mange liter vin har gutta produsert sålangt?",
    img: "5.JPG",
    answer: "B. 162L",
    options: ["A. 182L", "B. 162L", "C. 98L", "D. 203L"],
  },
  {
    numb: 6,
    question: "Hva er Ola ekspert på?",
    img: "6.JPG",
    answer: "D. Gjæringsprosesser",
    options: [
      "A. Mose druer",
      "B. Smakstesting",
      "C. Vinhistorie",
      "D. Gjæringsprosesser",
    ],
  },
  {
    numb: 7,
    question: "Hva er jobben til Gjerry?",
    img: "7.jpg",
    answer: "C. Estetisk arbeid",
    options: [
      "A. Skaffe investorer",
      "B. Økonomi",
      "C. Estetisk arbeid",
      "D. Kjøpe druer",
    ],
  },
  {
    numb: 8,
    question: "Hvilket syndrom har gjerry sosialantropologisk erfaring med?",
    img: "8.JPG",
    answer: "A. Trangt slips syndrom",
    options: [
      "A. Trangt slips syndrom",
      "B. Trang sløyfe syndrom",
      "C. Druemigrene",
      "D. Drueinfluensa",
    ],
  },
  {
    numb: 9,
    question: "Hvilken vin er best av Guttas Rouge og en Valpolicella?",
    img: "9.jpg",
    answer: "B. Guttas Rouge",
    options: ["A. Valpolicella", "B. Guttas Rouge"],
  },
  {
    numb: 10,
    question:
      "Hvor mange utgaver har gutta laget sålangt (se bort i fra den som er under brygg)?",
    img: "10.JPG",
    answer: "B. 6",
    options: ["A. 4", "B. 6", "C. 5", "D. 7"],
  },
  {
    numb: 11,
    question: "BONUS: Er gutta beast?",
    img: "11.JPG",
    answer: "Ja",
    options: ["Ja"],
  },
  {
    numb: 12,
    question: "EXTRA BONUS: Skal du kjøpe guttas nyttårsvin?",
    img: "12.JPG",
    answer: "Ja",
    options: ["Ja", "Nei"],
  },
];
